import { useEffect, useState } from 'react'
import axios from 'axios'

interface AIAnalysisProps {
  symbol: string
  analysisType?: 'short-term' | 'swing' | 'long-term'
}

interface SwingPrediction {
  hold_time_days: number
  hold_time_range: string
  potential_gain_pct: number
  potential_gain_range: string
  confidence_score: number
  key_levels: {
    support: number
    resistance: number
  }
  best_entry_zone: string
  exit_strategy: string
  risk_reward_ratio: number
}

export default function AIAnalysisReport({ symbol, analysisType = 'short-term' }: AIAnalysisProps) {
  const [report, setReport] = useState<string>('')
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [dataSummary, setDataSummary] = useState<any>(null)
  const [swingPrediction, setSwingPrediction] = useState<SwingPrediction | null>(null)

  useEffect(() => {
    if (!symbol) return

    const fetchAnalysis = async () => {
      setLoading(true)
      setError(null)

      try {
        const response = await axios.get(`/api/stocks/${symbol}/ai-analysis`)
        setReport(response.data.ai_analysis)
        setDataSummary(response.data.data_summary)

        // Fetch swing trade predictions if analysis type is swing
        if (analysisType === 'swing') {
          try {
            const swingResponse = await axios.get(`/api/stocks/${symbol}/swing-prediction`)
            setSwingPrediction(swingResponse.data)
          } catch (err) {
            console.error('Failed to fetch swing prediction:', err)
          }
        }
      } catch (err) {
        setError(`Failed to generate analysis: ${err}`)
      } finally {
        setLoading(false)
      }
    }

    fetchAnalysis()
  }, [symbol, analysisType])

  if (loading) {
    return (
      <div className="bg-gradient-to-br from-charcoal-700 to-charcoal-800 border border-gold-500 border-opacity-30 rounded-xl p-8">
        <div className="flex items-center justify-center space-x-3">
          <div className="animate-spin">
            <div className="text-gold-500 text-2xl">◆</div>
          </div>
          <div>
            <p className="text-gold-500 font-semibold">Generating AI Analysis with DeepSeek...</p>
            <p className="text-gray-400 text-sm">Analyzing {symbol} using AI intelligence</p>
          </div>
        </div>
      </div>
    )
  }

  if (error) {
    return (
      <div className="bg-red-950 border border-red-500 rounded-lg p-4 text-red-300 text-sm">
        {error}
      </div>
    )
  }

  return (
    <div className="space-y-6">
      {/* Report Header */}
      <div className="bg-gradient-to-r from-gold-600 to-gold-700 rounded-xl p-6 text-black">
        <h2 className="text-2xl font-black mb-2">🤖 AI-POWERED ANALYSIS</h2>
        <p className="text-sm opacity-90">
          {analysisType === 'swing'
            ? 'Swing Trade Predictions by DeepSeek AI | Hold Time & Gain Forecasts'
            : 'Generated by DeepSeek AI | Real-time data from Yahoo Finance'
          }
        </p>
      </div>

      {/* Data Summary Cards */}
      {dataSummary && (
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          <div className="bg-charcoal-900 rounded-lg p-4 border border-gold-500 border-opacity-20">
            <p className="text-gray-400 text-xs uppercase tracking-widest mb-1">Price</p>
            <p className="text-2xl font-bold text-gold-400">${dataSummary.current_price.toFixed(2)}</p>
          </div>
          <div className="bg-charcoal-900 rounded-lg p-4 border border-gold-500 border-opacity-20">
            <p className="text-gray-400 text-xs uppercase tracking-widest mb-1">RSI</p>
            <p className={`text-2xl font-bold ${dataSummary.rsi < 30 ? 'text-red-400' : dataSummary.rsi > 70 ? 'text-green-400' : 'text-yellow-400'}`}>
              {dataSummary.rsi.toFixed(1)}
            </p>
          </div>
          <div className="bg-charcoal-900 rounded-lg p-4 border border-gold-500 border-opacity-20">
            <p className="text-gray-400 text-xs uppercase tracking-widest mb-1">ADX</p>
            <p className="text-2xl font-bold text-blue-400">{dataSummary.adx.toFixed(1)}</p>
          </div>
          <div className="bg-charcoal-900 rounded-lg p-4 border border-gold-500 border-opacity-20">
            <p className="text-gray-400 text-xs uppercase tracking-widest mb-1">Momentum</p>
            <p className={`text-2xl font-bold ${dataSummary.momentum >= 0 ? 'text-green-400' : 'text-red-400'}`}>
              {dataSummary.momentum.toFixed(2)}
            </p>
          </div>
        </div>
      )}

      {/* Swing Trade Prediction */}
      {analysisType === 'swing' && swingPrediction && (
        <div className="bg-gradient-to-br from-purple-950 to-charcoal-800 border-2 border-purple-500 border-opacity-40 rounded-xl p-8">
          <h3 className="text-2xl font-bold text-purple-300 mb-6 flex items-center gap-2">
            <span>💫</span>
            SWING TRADE FORECAST
          </h3>

          {/* Key Predictions */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
            <div className="bg-charcoal-900 rounded-lg p-4 border-2 border-purple-500 border-opacity-30">
              <p className="text-gray-400 text-xs uppercase tracking-widest mb-2">Hold Duration</p>
              <p className="text-3xl font-black text-purple-300">{swingPrediction.hold_time_days} days</p>
              <p className="text-purple-300 text-xs mt-1">{swingPrediction.hold_time_range}</p>
            </div>

            <div className="bg-charcoal-900 rounded-lg p-4 border-2 border-green-500 border-opacity-30">
              <p className="text-gray-400 text-xs uppercase tracking-widest mb-2">Potential Gain</p>
              <p className="text-3xl font-black text-green-400">{swingPrediction.potential_gain_pct.toFixed(2)}%</p>
              <p className="text-green-300 text-xs mt-1">{swingPrediction.potential_gain_range}</p>
            </div>

            <div className="bg-charcoal-900 rounded-lg p-4 border-2 border-blue-500 border-opacity-30">
              <p className="text-gray-400 text-xs uppercase tracking-widest mb-2">Confidence</p>
              <p className="text-3xl font-black text-blue-400">{(swingPrediction.confidence_score * 100).toFixed(0)}%</p>
              <p className="text-blue-300 text-xs mt-1">AI Prediction Score</p>
            </div>
          </div>

          {/* Trade Details */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-6">
            <div className="bg-charcoal-900 rounded-lg p-4 border border-gold-500 border-opacity-20">
              <p className="text-gold-400 font-bold text-sm mb-3">Key Price Levels</p>
              <div className="space-y-2">
                <div className="flex justify-between">
                  <span className="text-gray-400">Support:</span>
                  <span className="text-green-400 font-bold">${swingPrediction.key_levels.support.toFixed(2)}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-gray-400">Resistance:</span>
                  <span className="text-red-400 font-bold">${swingPrediction.key_levels.resistance.toFixed(2)}</span>
                </div>
              </div>
            </div>

            <div className="bg-charcoal-900 rounded-lg p-4 border border-gold-500 border-opacity-20">
              <p className="text-gold-400 font-bold text-sm mb-3">Risk-Reward Ratio</p>
              <div className="space-y-2">
                <p className="text-2xl font-black text-gold-400">{swingPrediction.risk_reward_ratio.toFixed(2)}:1</p>
                <p className="text-gray-400 text-xs">Potential profit vs. loss ratio</p>
              </div>
            </div>
          </div>

          {/* Entry & Exit Strategy */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="bg-charcoal-900 rounded-lg p-4 border border-blue-500 border-opacity-20">
              <p className="text-blue-400 font-bold text-sm mb-2">Entry Zone</p>
              <p className="text-gray-300 text-sm">{swingPrediction.best_entry_zone}</p>
            </div>

            <div className="bg-charcoal-900 rounded-lg p-4 border border-orange-500 border-opacity-20">
              <p className="text-orange-400 font-bold text-sm mb-2">Exit Strategy</p>
              <p className="text-gray-300 text-sm">{swingPrediction.exit_strategy}</p>
            </div>
          </div>
        </div>
      )}

      {/* AI Report */}
      <div className="bg-gradient-to-br from-charcoal-700 to-charcoal-800 border border-gold-500 border-opacity-30 rounded-xl p-8">
        <div className="prose prose-invert max-w-none">
          <pre className="bg-charcoal-900 p-6 rounded-lg overflow-x-auto text-gray-300 text-sm leading-relaxed whitespace-pre-wrap break-words">
            {report}
          </pre>
        </div>
      </div>

      {/* Footer */}
      <div className="bg-charcoal-900 rounded-lg p-4 border border-gold-500 border-opacity-20">
        <p className="text-gray-400 text-xs">
          <span className="text-gold-400">⚠️ Disclaimer:</span> This AI analysis is for educational purposes only and should not be considered financial advice.
          Always conduct your own research and consult with a qualified financial advisor before making investment decisions.
        </p>
      </div>
    </div>
  )
}
